config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  get "static_pages/help"
  get "static_pages/about"

  namespace :admin do
    root "users#index"
    get "team_users/new"
    resources :users do
      resource :position_users, only: :show
      get "positions" => "position_users#show"
    end
    resources :teams do
      resource :team_users, only: :show
      get "members" => "team_users#show"
    end
    resources :imports
    resources :skills
    resources :projects
    resources :positions
  end
  resources :teams
  resources :users do
    resource :skill_users
    get "skills" => "skill_users#show"
  end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  extend Export
  include ActivityLogs

  has_many :users, through: :skill_users
  has_many :skill_users, dependent: :destroy

  validates :name, presence: true

  after_create :log_create
  after_update :log_update
  after_destroy :log_destroy

  def self.import file
    CSV.foreach(file.path, headers: true) do |row|
      skill = find_by_id(row["id"]) || new
      skill.attributes = row.to_hash.slice *row.to_hash.keys
      skill.save!
    end
  end
end

app/controllers/admin/skills_controller.rb
class Admin::SkillsController < ApplicationController
  before_action :set_skill, except: [:index, :new, :create]
  before_action :authenticate_user!, :admin_user

  def index
    @skills = Skill.all.paginate page: params[:page],
      per_page: Settings.paginate.normal
    respond_to do |format|
      format.html
      format.csv {send_data @skills.to_csv}
    end
  end

  def show
  end

  def new
    @skill = Skill.new
  end

  def edit
  end

  def create
    @skill = Skill.new skill_params
    respond_to do |format|
      if @skill.save
        format.html {redirect_to [:admin, @skill], notice: t("skill.create")}
      else
        format.html {render :new}
      end
    end
  end

  def update
    respond_to do |format|
      if @skill.update skill_params
        format.html {redirect_to [:admin, @skill], notice: t("skill.update")}
      else
        format.html {render :edit}
      end
    end
  end

  def destroy
    @skill.delete
    respond_to do |format|
      format.html {redirect_to admin_skills_url, notice: t("skill.delete")}
      format.json {head :no_content}
    end
  end

  private
  def set_skill
    @skill = Skill.find params[:id]
  end

  def skill_params
    params.require(:skill).permit :name, :description
  end
end

app/views/admin/skills/_form.html.erb
<%= form_for [:admin, @skill] do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/skills/_skill.html.erb
<tr>
  <td><%= link_to skill.name, admin_skill_path(skill) %></td>
  <td><%= skill.description %></td>
  <td><%= link_to t("user.show"), admin_skill_path(skill) %></td>
  <td><%= link_to t("user.edit"), edit_admin_skill_path(skill) %></td>
  <td><%= link_to t("user.delete"), admin_skill_path(skill), method: :delete,
    data: {confirm: t("user.confirm")} %></td>
</tr>

app/views/admin/skills/edit.html.erb
<h1><%= t "skill.editing_skill" %></h1>

<%= render "form" %>

<%= link_to t("user.show"), [:admin, @skill] %> |
<%= link_to t("user.back"), admin_skills_path %>

app/views/admin/skills/index.html.erb
<p id="notice"><%= notice %></p>
<h1><%= t "skill.listing_skill" %></h1>
<div class = "show-box">
  <table>
    <thead class="t-header">
      <tr>
        <th><%= t "skill.name" %></th>
        <th><%= t "skill.description" %></th>
        <th colspan="3" class="th-colspan"></th>
      </tr>
    </thead>

    <tbody class="t-body">
      <%= render partial: "skill", collection: @skills %>
      <%= will_paginate %>
    </tbody>
  </table>
  <%= link_to t("skill.new_skill"), new_admin_skill_path %>
</div>

<%= render "shared/import", _model: Position %>

app/views/admin/skills/new.html.erb
<h1><%= t "skill.new_skill" %></h1>

<%= render "form" %>

<%= link_to t("user.back"), admin_skills_path %>

app/views/admin/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t "skill.name" %></strong>
  <%= @skill.name %>
</p>

<p>
  <strong><%= t "skill.description" %></strong>
  <%= @skill.description %>
</p>

<%= link_to t("user.edit"), edit_admin_skill_path(@skill) %> |
<%= link_to t("user.back"), admin_skills_path %>