config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  get "static_pages/help"
  get "static_pages/about"

  namespace :admin do
    root "users#index"
    get "team_users/new"
    resources :users do
      resource :position_users, only: :show
      get "positions" => "position_users#show"
    end
    resources :teams do
      resource :team_users, only: :show
      get "members" => "team_users#show"
    end
    resources :imports
    resources :skills
    resources :projects
    resources :positions
  end
  resources :teams
  resources :users do
    resource :skill_users
    get "skills" => "skill_users#show"
  end
end

app/models/position.rb
class Position < ActiveRecord::Base
  extend Export
  include ActivityLogs

  has_many :users, through: :position_users
  has_many :position_users, dependent: :destroy

  validates :name, presence: true

  after_create :log_create
  after_update :log_update
  after_destroy :log_destroy
end

app/controllers/admin/positions_controller.rb
class Admin::PositionsController < ApplicationController
  before_action :set_position, except: [:index, :new, :create]
  before_action :authenticate_user!, :admin_user

  def index
    @positions = Position.all.paginate page: params[:page],
      per_page: Settings.paginate.normal
    respond_to do |format|
      format.html
      format.csv {send_data @positions.to_csv}
    end
  end

  def show
    @position = Position.find params[:id]
    @users = @position.users
  end

  def new
    @position = Position.new
  end

  def edit
  end

  def create
    @position = Position.new position_params
    respond_to do |format|
      if @position.save
        format.html {redirect_to [:admin, @position], notice: t("position.create")}
      else
        format.html {render :new}
      end
    end
  end

  def update
    respond_to do |format|
      if @position.update position_params
        format.html {redirect_to [:admin, @position], notice: t("position.update")}
      else
        format.html {render :edit}
      end
    end
  end

  def destroy
    @position.delete
    respond_to do |format|
      format.html {redirect_to admin_positions_url, notice: t("position.delete")}
      format.json {head :no_content}
    end
  end

  private
  def set_position
    @position = Position.find params[:id]
  end

  def position_params
    params.require(:position).permit :name, :abbreviation
  end
end

app/views/admin/positions/_form.html.erb
<%= form_for [:admin, @position] do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :abbreviation %><br>
    <%= f.text_area :abbreviation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/positions/_position.html.erb
<tr>
  <td><%= link_to position.name, admin_position_path(position) %></td>
  <td><%= position.abbreviation %></td>
  <td><%= link_to t("user.show"), admin_position_path(position) %></td>
  <td><%= link_to t("user.edit"), edit_admin_position_path(position) %></td>
  <td><%= link_to t("user.delete"), admin_position_path(position),
    method: :delete, data: {confirm: t("user.confirm")} %></td>
</tr>

app/views/admin/positions/edit.html.erb
<h1><%= t "position.editing_position" %></h1>

<%= render "form" %>

<%= link_to t("user.show"), [:admin, @position] %> |
<%= link_to t("user.back"), admin_positions_path %>

app/views/admin/positions/index.html.erb
<p id="notice"><%= notice %></p>
<h1><%= t "position.listing_position" %></h1>
<div class = "show-box">
  <table>
    <thead class="t-header">
      <tr>
        <th><%= t "position.name" %></th>
        <th><%= t "position.abbreviation" %></th>
        <th colspan="3" class="th-colspan"></th>
      </tr>
    </thead>

    <tbody class="t-body">
      <%= render partial: "position", collection: @positions %>
      <%= will_paginate %>
    </tbody>
  </table>
  <%= link_to t("position.new_position"), new_admin_position_path %>
</div>

<%= render "shared/import", _model: Position %>

app/views/admin/positions/new.html.erb
<h1><%= t "position.new_position" %></h1>
<%= render "form" %>
<%= link_to t("user.back"), admin_positions_path %>

app/views/admin/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t "position.name" %></strong>
  <%= @position.name %>
</p>

<p>
  <strong><%= t "position.abbreviation" %></strong>
  <%= @position.abbreviation %>
</p>

<%= link_to t("user.edit"), edit_admin_position_path(@position) %> |
<%= link_to t("user.back"), admin_positions_path %>