config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  get "static_pages/help"
  get "static_pages/about"

  namespace :admin do
    root "users#index"
    get "team_users/new"
    resources :users do
      resource :position_users, only: :show
      get "positions" => "position_users#show"
    end
    resources :teams do
      resource :team_users, only: :show
      get "members" => "team_users#show"
    end
    resources :imports
    resources :skills
    resources :projects
    resources :positions
  end
  resources :teams
  resources :users do
    resource :skill_users
    get "skills" => "skill_users#show"
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend Export
  include ActivityLogs

  has_many :users, through: :project_users
  has_many :project_users, dependent: :destroy
  belongs_to :team

  validates :name, presence: true
  validates :team_id, presence: true

  after_save :assign_user
  after_create :log_create
  after_update :log_update
  after_destroy :log_destroy

  private
  def assign_user
    team.users.each{|user| project_users.create! user: user, joined_date: start_date}
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  before_action :set_project, except: [:index, :new, :create]
  before_action :authenticate_user!, :admin_user

  def index
    @projects = Project.all.paginate page: params[:page],
      per_page: Settings.paginate.normal
    respond_to do |format|
      format.html
      format.csv {send_data @projects.to_csv}
    end
  end

  def show
    @users = @project.users
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new project_params
    respond_to do |format|
      if @project.save
        format.html {redirect_to [:admin, @project], notice: t("project.create")}
      else
        format.html {render :new}
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update project_params
        format.html {redirect_to [:admin, @project], notice: t("project.update")}
      else
        format.html {render :edit}
      end
    end
  end

  def destroy
    @project.delete
    respond_to do |format|
      format.html {redirect_to admin_projects_url, notice: t("project.delete")}
      format.json {head :no_content}
    end
  end

  private
  def set_project
    @project = Project.find params[:id]
  end

  def project_params
    params.require(:project).permit :team_id, :name, :description, :start_date, :end_date
  end
end

app/views/admin/projects/_form.html.erb
<%= form_for [:admin, @project] do |f| %>
  <div class="field">
    <%= f.label :team_id, "Team" %>
    <%= f.collection_select :team_id, Team.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_date %>
    <%= f.datetime_field :start_date, class: "datepicker" %>
  </div>
  <div class="field">
    <%= f.label :end_date %>
    <%= f.datetime_field :end_date, class: "datepicker" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/projects/_project.html.erb
<tr>
  <td><%= project.team_id %></td>
  <td><%= link_to project.name, admin_project_path(project) %></td>
  <td><%= project.description %></td>
  <td><%= link_to t("user.show"), admin_project_path(project) %></td>
  <td><%= link_to t("user.edit"), edit_admin_project_path(project) %></td>
  <td><%= link_to t("user.delete"), admin_project_path(project), method: :delete,
    data: {confirm: t("user.confirm")} %></td>
</tr>

app/views/admin/projects/_user.html.erb
<tr>
  <td><%= user.id %></td>
  <td><%= link_to user.email, admin_user_path(user) %></td>
</tr>

app/views/admin/projects/edit.html.erb
<h1><%= t "project.editing_project" %></h1>
<%= render "form" %>
<%= link_to t("user.show"), [:admin, @project] %> |
<%= link_to t("user.back"), admin_projects_path %>

app/views/admin/projects/index.html.erb
<p id="notice"><%= notice %></p>
<h1><%= t "project.listing_project" %></h1>
<div class = "show-box">
  <div id="projects-list">
    <table>
      <thead class="t-header">
        <tr>
          <th><%= t "project.team_id" %></th>
          <th><%= t "project.name" %></th>
          <th><%= t "project.description" %></th>
          <th colspan="3" class="th-colspan"></th>
        </tr>
      </thead>
      <tbody class="t-body">
        <%= render partial: "project", collection: @projects %>
      </tbody>
    </table>
    <%= will_paginate %>
  </div>
  <%= link_to t("project.new_project"), new_admin_project_path %>
</div>

<%= render "shared/import", _model: Project %>

app/views/admin/projects/new.html.erb
<h1><%= t "project.new_project" %></h1>
<%= render "form" %>
<%= link_to t("user.back"), admin_projects_path %>

app/views/admin/projects/show.html.erb
<p id="notice"><%= notice %></p>
<aside class= "col-md-6">
  <p>
    <strong><%= t "project.team_id: " %></strong>
    <%= @project.team_id %>
  </p>
  <p>
    <strong><%= t "project.name: " %></strong>
    <%= @project.name %>
  </p>
  <p>
    <strong><%= t "project.description: " %></strong>
    <%= @project.description %>
  </p>
  <p>
    <strong><%= t "project.start_date: " %></strong>
    <%= @project.start_date %>
  </p>
  <p>
    <strong><%= t "project.end_date: " %></strong>
    <%= @project.end_date %>
  </p>

  <%= link_to t("user.edit"), edit_admin_project_path(@project) %> |
  <%= link_to t("user.back"), admin_projects_path %>
</aside>
<aside class= "col-md-6">
  <h1><%= t "project.list_user" %></h1>
  <table>
    <thead class="t-header">
      <tr>
        <th class="th1"><%= t "user.id" %></th>
        <th class="th2"><%= t "user.email" %></th>
        <th colspan="3" class="th-colspan"></th>
      </tr>
    </thead>
    <tbody class="t-body">
      <%= render partial: "user", collection: @users %>
    </tbody>
  </table>
</aside>