config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "static_pages#home"
  get "static_pages/help"
  get "static_pages/about"

  namespace :admin do
    root "users#index"
    get "team_users/new"
    resources :users do
      resource :position_users, only: :show
      get "positions" => "position_users#show"
    end
    resources :teams do
      resource :team_users, only: :show
      get "members" => "team_users#show"
    end
    resources :imports
    resources :skills
    resources :projects
    resources :positions
  end
  resources :teams
  resources :users do
    resource :skill_users
    get "skills" => "skill_users#show"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :positions, through: :position_users
  has_many :position_users, dependent: :destroy
  has_many :teams, through: :team_users
  has_many :team_users, dependent: :destroy
  has_many :projects, through: :project_users
  has_many :project_users, dependent: :destroy

  query = "id not in (select user_id from team_users)"
  scope :not_in_team, ->{where query}

  has_many :teams, through: :team_users
  has_many :team_users, dependent: :destroy

  has_many :skills, through: :skill_users
  has_many :skill_users, dependent: :destroy

  accepts_nested_attributes_for :position_users, allow_destroy: true
  accepts_nested_attributes_for :team_users, allow_destroy: true
  accepts_nested_attributes_for :skill_users, allow_destroy: true

  Settings.roles.each do |v|
    define_method("is_#{v}?") {role == v}
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @search = User.search params[:q]
    @users = @search.result.paginate page: params[:page],
      per_page: Settings.paginate.small
    @activities = Activity.all
  end

  def show
    @user = User.find params[:id]
    @positions = @user.positions
    @teams = @user.teams
    @skills = @user.skills
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "flash.added"
      redirect_to admin_users_url
    else
      render "new"
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes user_params
      flash[:success] = t "flash.update"
      redirect_to admin_users_url
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy
    flash[:notice] = t "flash.delete"
    redirect_to admin_users_path
  end

  private
  def user_params
    params.require(:user).permit :email, :password,
      :password_confirmation, :role, position_ids: []
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
    @teams = @user.teams
  end

  def update
    if @user.update_attributes user_params
      respond_to do |format|
        format.html {redirect_to user_skills_path(@user)}
        format.js
      end
    else
      flash[:success] = t "flash.notupdate"
    end
  end

  private
  def set_user
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit :email, :password, skill_ids: [],
      skill_users_attributes: [:id, :skill_id, :level, :year, :_destroy]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_activity.html.erb
<% @activities.each do |l| %>
  <%= l.action %>
  <%= l.object %>
  <%= l.created_at %>
  <br>
<% end %>

app/views/admin/users/_export_csv.html.erb
<p>
  <%= t "user.download_skill" %>
  <%= link_to t("user.csv"), admin_skills_path(format: "csv") %>
</p>
<p>
  <%= t "user.download_team" %>
  <%= link_to t("user.csv"), admin_teams_path(format: "csv") %>
</p>
<p>
  <%= t "user.download_project" %>
  <%= link_to t("user.csv"), admin_projects_path(format: "csv") %>
</p>
<p>
  <%= t "user.download_position" %>
  <%= link_to t("user.csv"), admin_positions_path(format: "csv") %>
</p>

app/views/admin/users/_import.html.erb
<%= flash[:notice] %>
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    <% @users_csv.each do |u| %>
      <tr>
        <td><%= u.id %></td>
        <td><%= u.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
<h3>Import a CSV File</h3>
  <%= form_tag import_admin_users_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV" %>
  <% end %>
</div>

<%= flash[:notice] %>
<div>
  <h3><%= t "import.import_file" %></h3>
  <%= form_tag import_admin_users_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag t"import.submit_tag" %>
  <% end %>
</div>

app/views/admin/users/_result.html.erb
<h4><%= t "user.result" %><h4>
<% @users.each do |user| %>
  <%= link_to user.email, user %> |
  <td><%= link_to t("user.delete"), admin_user_path(user), method: :delete,
    data: {confirm: t("user.confirm")} %></td>
  <br>
<% end %>
<%= will_paginate %>

app/views/admin/users/_search.html.erb
<%= search_form_for @search, url: admin_users_path do |f| %>
  <fieldset>
    <ul>
      <li>
        <%= f.label :email_cont %>
        <%= f.text_field :email_cont %>
      </li>
    </ul>
  </fieldset>
  <%= f.submit t("user.search"), class: "btn btn-primary" %>
<% end %>

app/views/admin/users/index.html.erb
<h1><%= t "user.all_user" %></h1>

<div id = "search">
  <div class = "search-box">
    <%= render "search" %>
  </div>

  <div class = "search-result">
    <%= render "result" %>
  </div>
</div>

<div id = "activity-and-export">
  <div class = "activity-log">
    <h3><%= t "activity.list" %></h3>
    <marquee bgcolor="#C0C0C0" onMouseOver="this.scrollAmount=0"
      onMouseOut="this.scrollAmount=2" scrollamount="2" direction="up"
      loop="true" width="80%">
      <center>
      <%= render "activity" %>
      </center>
    </marquee>
  </div>

  <div class = "export-csv">
    <%= render "export_csv" %>
  </div>
</div>

<div>

</div>

app/views/admin/users/show.html.erb
<h1><%= t "user.profile" %></h1>
  <div>
    <h3><%= t "user.email" %></h3>
    <h2><%= @user.email %></h2>
  </div>
  <div>
    <h3><%= t "user.positions" %></h3>
      <% @positions.each do |n| %>
        <%= n.name %>
      <% end %>
    </h2>
  </div>
  <div>
    <h3><%= t "user.skill" %></h3>
    <h2>
      <% @skills.each do |n| %>
        <%= n.name %> |
      <% end %>
    </h2>
  </div>
  <%= link_to t("user.add_position"), admin_user_position_users_path(@user), class: "btn btn-primary" %>
  <div class="box-content">
    <ul class="account_list">
      <li><%= link_to t("user.list-team"), admin_teams_path %></li>
    </ul>
  </div>